apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-api-config
  labels:
    app: oficina-api
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8000"
  JWKS_URL: "https://oficina-gateway-dkvx20rp.ue.gateway.dev/.well-known/jwks.json"
