apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secret
  labels:
    app: oficina-api
type: Opaque
stringData:
  DATABASE_URL: "DB_URL_PLACEHOLDER"
  JWT_SECRET: "changeme-secret-key-for-admin-token-min-32-chars"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_MINUTES: "60"
