apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secret
  labels:
    app: oficina-api
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://oficina_user:changeme@10.0.0.3:5432/oficina_prod"
  JWT_SECRET: "changeme-secret-key-for-admin-token-min-32-chars"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_MINUTES: "60"
